#!/bin/bash
#chkconfig: 2345 20 80
# description: Jool SIIT Configuration Service

# Source function library
. /etc/init.d/functions

start(){
  /sbin/modprobe jool_siit pool6=2001:db8::/96
}

stop(){
  /sbin/modprobe -r jool_siit
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
	start
    ;;
  status)
    /usr/local/bin/jool_siit 
    ;;
  *)	

echo "Usage: $0 {start|stop|status|restart}"

esac

exit 0